services:
  web:
    container_name: mh-client
    depends_on:
      - api
    build: ./client
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync
    restart: unless-stopped

  api:
    container_name: mh-server
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.debug
    ports:
      - 5500:5500
      - 9229:9229
    env_file:
      - ./server/.env
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync
    restart: unless-stopped

  db:
    container_name: mh-postgres
    image: postgres:17.4-alpine
    ports:
      - 5433:5432
    env_file:
      - ./server/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: mh-redis
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  db_data:
