services:
  web:
    depends_on:
      - api
    build: ./client
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    build: ./server
    ports:
      - 5500:5500
    env_file:
      - ./server/.env
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync
